# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: secureliCI

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Validate Branch name
      run: ./scripts/get-current-branch.sh
    - name: Set up Python 3.9
      id: setup-python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Set Up Project
      run: |
        pip install poetry
        poetry install
    - name: Run Tests
      run: |
        poetry run poe precommit
        poetry run poe coverage
        poetry run secureli yeti
    - name: Checkout Python secrets repo
      uses: actions/checkout@v3
      with: 
        repository: asidiehl/python-secrets
        path: python-secrets
    - name: Test secret detection for Python
      run: |
        pre-commit run detect-secrets --files python-secrets/*
    - name: Semantic Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        pip install python-semantic-release
        git config user.name github-actions
        git config user.email github-actions@github.com
        semantic-release publish
    # A NOOP run on feature branches
    - name: Verify Semantic Release
      if: github.ref != 'refs/heads/main'
      run: |
        export GH_TOKEN=${{ secrets.ADMIN_TOKEN_SASCHA }}
        pip install python-semantic-release
        git config user.name github-actions
        git config user.email github-actions@github.com
        semantic-release publish --noop
    # - name: Verify SemVer Release
    #   if: github.ref != 'refs/heads/main'
    #   uses: relekang/python-semantic-release@master
    #   with:
    #     github_token: ${{ secrets.ADMIN_TOKEN_SASCHA }}
    #     additional_options: --noop
    # - name: SemVer Version Release
    #   if: github.ref == 'refs/heads/main'
    #   uses: relekang/python-semantic-release@master
    #   with:
    #     github_token: ${{ secrets.ADMIN_TOKEN_SASCHA }}


  # test-python-repo:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out SeCureLI
  #     uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0
  #   - name: Set up Python 3.9
  #     id: setup-python
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: "3.9"
  #   - name: Set Up Project
  #     run: |
  #       pip install poetry
  #       poetry install
  #   - name: Run Tests
  #     run: |
  #       pre-commit run detect-secrets
        